users_name = input()
users_age = input()
users_hometown = input()
users_major = input()
users_hobby = input()
users_expected_graduation_year = input()

print("=== YOUR DIGITAL PROFILE ===")
print(f"Name: {users_name}")
print(f"Age: {users_age} years old")
print(f"Hometown: {users_hometown}")
print(f"Major: {users_major}")
print(f"Hobby: {users_hobby}")
print(f"Expected Graduation: {users_expected_graduation_year}")
print("Thanks for setting up your profile!")