users_name = input()
users_age = input()
users_hometown = input()
users_major = input()
users_hobby = input()
users_expected_graduation_year = input()

print("=== YOUR DIGITAL PROFILE ===")
print("Name: {users_name}")
print("Age: {users_age} years old")
print("Hometown: {users_hometown}")
print("Major: {users_major}")
print("Hobby: {users_hobby}")
print("Expected Graduation: {users_expected_graduation_year}")
print("Thanks for setting up your profile!")